In [1]:
!pip install requests beautifulsoup4 pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests) (2024.8.30)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = "https://countrycode.org/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html")

In [4]:
response

In [5]:
response.text

'\n\n<!DOCTYPE html>\n<!--[if IE 8]>         <html class="ie8" lang="en"> <![endif]-->\n<!--[if IE 9]>         <html class="ie9" lang="en"> <![endif]-->\n<!--[if gt IE 9]><!--> <html lang="en">         <!--<![endif]-->\n    <head>\n        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n        <title>CountryCode.org: Country Codes, Phone Codes, Dialing Codes, Telephone Codes, ISO Country Codes</title>\n        \n        <meta name="viewport" content="width=device-width, initial-scale=1">\n        \n        <meta name="title" content="CountryCode.org: Country Codes, Phone Codes, Dialing Codes, Telephone Codes, ISO Country Codes"/>\n        <meta name="description" content="Find more information about country codes, phone codes, and ISO country codes. We&#39;ve got the phone codes you need for easy international calling!"/>\n        <meta property="og:type" content="website"/>\n        <meta property="og:site_name" content="CountryCode.org"/>\n        <meta property="og:url" content="https://countrycode.org/"/>\n        <meta property="og:title" content="Country Codes, Phone Codes, Dialing Codes, Telephone Codes, ISO Country Codes"/>\n        <meta property="og:description" content="Find more information about country codes, phone codes, and ISO country codes. We&#39;ve got the phone codes you need for easy international calling!"/>\n        <meta property="og:image" content="https://countrycode.org/static/images/cc-og-image.jpg"/>\n        <meta property="og:image:width" content="1200"/>\n        <meta property="og:image:height" content="630"/>\n        <meta property="og:image:alt" content="Get Your New International Toll Free Number"/>\n\n        \n        <link rel="canonical" href="https://countrycode.org/"/>\n\n        <!-- Favicon -->\n        <link rel="shortcut icon" type="image/x-icon" rel="stylesheet" href="/static/images/favicon.ico" />\n\n        \n        <link  rel="stylesheet" href="/global-shared/static/global-icons/font-awesome/css/font-awesome.min_900fdb111f.css" />\n        <link  rel="stylesheet" href="/global-shared/static/global-icons/entypo/css/entypo.min_900fdb111f.css" />\n\n        \n        <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">\n        <link  rel="stylesheet" href="/static/css/site_900fdb111f.css" />\n        <link  rel="stylesheet" href="/global-shared/static/bootstrap-select-1.13.0/css/bootstrap-select.min_900fdb111f.css" />\n\n        \n        <script nonce="5cf8e433-0adf-4ef3-831d-34af9a28ca55" src="/global-shared/static/modernizr/modernizr-2.8.3_900fdb111f.js" type="text/javascript" ></script>\n\n        \n        \n<script nonce="5cf8e433-0adf-4ef3-831d-34af9a28ca55" src="/global-shared/static/jquery-3.7.1/jquery-3.7.1.min_900fdb111f.js" type="text/javascript" ></script>\n\n<script nonce="5cf8e433-0adf-4ef3-831d-34af9a28ca55" src="/global-shared/static/jquery-3.7.1/jquery-migrate-3.5.2.min_900fdb111f.js" type="text/javascript" ></script>\n\n        \n        <script nonce="5cf8e433-0adf-4ef3-831d-34af9a28ca55" src="//cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>\n        <script nonce="5cf8e433-0adf-4ef3-831d-34af9a28ca55" src="//stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>\n        <script nonce="5cf8e433-0adf-4ef3-831d-34af9a28ca55" src="/global-shared/static/bootstrap-select-1.13.0/js/bootstrap-select.min_900fdb111f.js" type="text/javascript" ></script>\n\n        <script nonce="5cf8e433-0adf-4ef3-831d-34af9a28ca55" src="/static/js/bootstrap-table.min_900fdb111f.js" type="text/javascript" ></script>\n\n        <script nonce="5cf8e433-0adf-4ef3-831d-34af9a28ca55" src="/static/js/site_900fdb111f.js" type="text/javascript" ></script>\n\n        \n        \n    <meta name="layout" content="site-countrycode"/>\n    \n    <meta name="description" content="Find more information about country codes, phone codes, and ISO country codes. We&#39;ve got the phone codes you need for easy international calling!"/>\n    <meta name="keywords" content="Country Codes, Phone Codes, Dialing Codes, Telephone Codes, ISO Country Codes"/>\n\n\n        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n        <!--[if lt IE 9]>\n            <script nonce="5cf8e433-0adf-4ef3-831d-34af9a28ca55" src="/global-shared/static/html5shiv-3.7.2.min_900fdb111f.js" type="text/javascript" ></script>\n\n            <script nonce="5cf8e433-0adf-4ef3-831d-34af9a28ca55" src="/global-shared/static/respond-1.4.2.min_900fdb111f.js" type="text/javascript" ></script>\n\n        <![endif]-->\n        <script nonce=\'5cf8e433-0adf-4ef3-831d-34af9a28ca55\'>\n  (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){\n  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n  m=s.getElementsByTagName(o)[0];a.setAttribute("nonce","5cf8e433-0adf-4ef3-831d-34af9a28ca55");a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n  })(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\');\n\n  ga(\'create\', \'UA-10878761-1\', \'auto\');\n  ga(\'send\', \'pageview\');\n\n</script>\n    \n        <style>#swfcontainer, #myswf {position:absolute; top: 1px; left: 1px}</style>\n    </head>\n    <body class="" data-theme="">\n        <script nonce="5cf8e433-0adf-4ef3-831d-34af9a28ca55" src="/global-shared/static/scriptLoader_900fdb111f.js" type="text/javascript" ></script>\n\n        \n        \n        \n\n<div class="header">\n    <div class="container">\n        <div class="row">\n\n            <div class="col-md-4">\n                <a href="/" class="logo">CountryCode<sub>.org</sub></a>\n            </div>\n\n            <!-- Hidden on Mobile -->\n            <div class="col-md-8 d-none d-lg-block">\n                <div class="row">\n                    <div class="col-md-9 search-bar d-none countrynav-container">\n                        <div id="countrynav-bar">\n                            <label for="countrySelect" class="sr-only">Select A Country</label>\n                            <select id="countrySelect" class="countrynav country-picker-large form-control countrymenu countrynav-only" data-live-search="true" data-size="9" data-content="">\n                                <option data-icon="fa fa-search">SELECT A COUNTRY</option>\n                            </select>\n                        </div>\n                    </div>\n                    <div class="col pull-right">\n                        <ul class="list-unstyled list-inline list-social pull-right">\n                            <li class="list-inline-item mr-0"><a href="https://www.facebook.com/countrycodeguide" target="_blank" ><img src="/static/images/i-facebook_900fdb111f.png" width="32" height="32" alt="Facebook" title=""/></a></li>\n                            <li class="list-inline-item mr-0"><a href="https://twitter.com/CountryCode101" target="_blank"><img src="/static/images/i-twitter_900fdb111f.png" width="32" height="32" alt="Twitter" title=""/></a></li>\n                            <li class="list-inline-item mr-0"><a href="https://plus.google.com/u/0/b/117317105484240817855/117317105484240817855/" target="_blank"><img src="/static/images/i-google_900fdb111f.png" width="32" height="32" alt="Google+" title=""/></a></li>\n                        </ul>\n                    </div>\n                </div> <!-- closes .row -->\n            </div>\n\n        </div> <!-- closes .row -->\n    </div> <!-- closes .container-fluid -->\n</div> <!-- closes .header -->\n\n\n        \n    \n\n    \n    <div class="jumbotron rounded-0">\n        <div class="container">\n            <div class="row">\n                <div class="col-sm-6 offset-sm-3 text-center">\n                    <div class="box box-search countrynav-container"></div>\n                </div>\n            </div>\n        </div>\n    </div>\n\n    <div class="container">\n        <h2 class="text-center">Country Codes</h2>\n\n        <!-- Hide On Mobile View-->\n        <div class="d-none d-lg-block">\n            <!--CONTENT TABLE-->\n            <table class="table table-hover table-striped main-table"\n                data-toggle="table"\n                data-sort-name="countrycode"\n                data-sort-order="desc">\n                <thead>\n                    <tr>\n                        <th\n                            data-field="name"\n                            data-sortable="true">\n                            COUNTRY\n                        </th>\n                        <th\n                            data-field="code"\n                            data-sortable="true"\n                            data-formatter="country_code"\n                            data-sorter="code_sort">\n                            COUNTRY CODE\n                        </th>\n                        <th\n                            data-field="iso"\n                            data-sortable="true">\n                            ISO CODES\n                        </th>\n                        <th class="population-col"\n                            data-field="population"\n                            data-sortable="true"\n                            data-sorter="population_sort">\n                            POPULATION\n                        </th>\n                        <th\n                            data-field="area"\n                            data-sortable="true"\n                            data-sorter="population_sort">\n                            AREA KM<span class="superscript">2</span>\n                        </th>\n                        <th\n                            data-field="gdp"\n                            data-sortable="true"\n                            data-sorter="gdp_sort_named">\n                            GDP $USD\n                        </th>\n                        \n                        \n                    </tr>\n                </thead>\n            <tbody>\n                \n                <tr>\n                    <td><a href="/afghanistan">Afghanistan</a></td>\n                    <td>93</td>\n                    <td>AF / AFG</td>\n                    <td>29,121,286</td>\n                    <td>647,500</td>\n                    <td>20.65 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/albania">Albania</a></td>\n                    <td>355</td>\n                    <td>AL / ALB</td>\n                    <td>2,986,952</td>\n                    <td>28,748</td>\n                    <td>12.8 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/algeria">Algeria</a></td>\n                    <td>213</td>\n                    <td>DZ / DZA</td>\n                    <td>34,586,184</td>\n                    <td>2,381,740</td>\n                    <td>215.7 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/americansamoa">American Samoa</a></td>\n                    <td>1-684</td>\n                    <td>AS / ASM</td>\n                    <td>57,881</td>\n                    <td>199</td>\n                    <td>462.2 Million</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/andorra">Andorra</a></td>\n                    <td>376</td>\n                    <td>AD / AND</td>\n                    <td>84,000</td>\n                    <td>468</td>\n                    <td>4.8 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/angola">Angola</a></td>\n                    <td>244</td>\n                    <td>AO / AGO</td>\n                    <td>13,068,161</td>\n                    <td>1,246,700</td>\n                    <td>124 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/anguilla">Anguilla</a></td>\n                    <td>1-264</td>\n                    <td>AI / AIA</td>\n                    <td>13,254</td>\n                    <td>102</td>\n                    <td>175.4 Million</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/antarctica">Antarctica</a></td>\n                    <td>672</td>\n                    <td>AQ / ATA</td>\n                    <td>0</td>\n                    <td>14,000,000</td>\n                    <td></td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/antiguaandbarbuda">Antigua and Barbuda</a></td>\n                    <td>1-268</td>\n                    <td>AG / ATG</td>\n                    <td>86,754</td>\n                    <td>443</td>\n                    <td>1.22 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/argentina">Argentina</a></td>\n                    <td>54</td>\n                    <td>AR / ARG</td>\n                    <td>41,343,201</td>\n                    <td>2,766,890</td>\n                    <td>484.6 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/armenia">Armenia</a></td>\n                    <td>374</td>\n                    <td>AM / ARM</td>\n                    <td>2,968,000</td>\n                    <td>29,800</td>\n                    <td>10.44 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/aruba">Aruba</a></td>\n                    <td>297</td>\n                    <td>AW / ABW</td>\n                    <td>71,566</td>\n                    <td>193</td>\n                    <td>2.516 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/australia">Australia</a></td>\n                    <td>61</td>\n                    <td>AU / AUS</td>\n                    <td>21,515,754</td>\n                    <td>7,686,850</td>\n                    <td>1.488 Trillion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/austria">Austria</a></td>\n                    <td>43</td>\n                    <td>AT / AUT</td>\n                    <td>8,205,000</td>\n                    <td>83,858</td>\n                    <td>417.9 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/azerbaijan">Azerbaijan</a></td>\n                    <td>994</td>\n                    <td>AZ / AZE</td>\n                    <td>8,303,512</td>\n                    <td>86,600</td>\n                    <td>76.01 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/bahamas">Bahamas</a></td>\n                    <td>1-242</td>\n                    <td>BS / BHS</td>\n                    <td>301,790</td>\n                    <td>13,940</td>\n                    <td>8.373 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/bahrain">Bahrain</a></td>\n                    <td>973</td>\n                    <td>BH / BHR</td>\n                    <td>738,004</td>\n                    <td>665</td>\n                    <td>28.36 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/bangladesh">Bangladesh</a></td>\n                    <td>880</td>\n                    <td>BD / BGD</td>\n                    <td>156,118,464</td>\n                    <td>144,000</td>\n                    <td>140.2 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/barbados">Barbados</a></td>\n                    <td>1-246</td>\n                    <td>BB / BRB</td>\n                    <td>285,653</td>\n                    <td>431</td>\n                    <td>4.262 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/belarus">Belarus</a></td>\n                    <td>375</td>\n                    <td>BY / BLR</td>\n                    <td>9,685,000</td>\n                    <td>207,600</td>\n                    <td>69.24 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/belgium">Belgium</a></td>\n                    <td>32</td>\n                    <td>BE / BEL</td>\n                    <td>10,403,000</td>\n                    <td>30,510</td>\n                    <td>507.4 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/belize">Belize</a></td>\n                    <td>501</td>\n                    <td>BZ / BLZ</td>\n                    <td>314,522</td>\n                    <td>22,966</td>\n                    <td>1.637 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/benin">Benin</a></td>\n                    <td>229</td>\n                    <td>BJ / BEN</td>\n                    <td>9,056,010</td>\n                    <td>112,620</td>\n                    <td>8.359 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/bermuda">Bermuda</a></td>\n                    <td>1-441</td>\n                    <td>BM / BMU</td>\n                    <td>65,365</td>\n                    <td>53</td>\n                    <td>5.6 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/bhutan">Bhutan</a></td>\n                    <td>975</td>\n                    <td>BT / BTN</td>\n                    <td>699,847</td>\n                    <td>47,000</td>\n                    <td>2.133 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/bolivia">Bolivia</a></td>\n                    <td>591</td>\n                    <td>BO / BOL</td>\n                    <td>9,947,418</td>\n                    <td>1,098,580</td>\n                    <td>30.79 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/bosnia">Bosnia and Herzegovina</a></td>\n                    <td>387</td>\n                    <td>BA / BIH</td>\n                    <td>4,590,000</td>\n                    <td>51,129</td>\n                    <td>18.87 Billion</td>\n                    \n                </tr>\n                \n                <tr>\n                    <td><a href="/botswana">Botswana</a></td>\n                    <td>267</td>\n                    <td>BW / BWA</td>\n                    <td>2,029,307</td>\n                    <td>600,370</td>\n                    <td>15.53 Billion</td>\n                    \n                </tr>\n              

In [6]:
table = soup.find("table")

headers = [th.text.strip() for th in table.find_all("th")]

rows = []
for tr in table.find_all("tr")[1:]:  # skip header row
    cols = tr.find_all("td")
    # if no <td> then skip
    if len(cols) == 0:
        continue
    row = [ele.text.strip() for ele in cols]
    rows.append(row)

df = pd.DataFrame(rows, columns=headers)
df.head()

          COUNTRY COUNTRY CODE ISO CODES  POPULATION   AREA KM2       GDP $USD
0     Afghanistan           93  AF / AFG  29,121,286    647,500  20.65 Billion
1         Albania          355  AL / ALB   2,986,952     28,748   12.8 Billion
2         Algeria          213  DZ / DZA  34,586,184  2,381,740  215.7 Billion
3  American Samoa        1-684  AS / ASM      57,881        199  462.2 Million
4         Andorra          376  AD / AND      84,000        468    4.8 Billion

In [7]:
df.to_csv("countrycodes.csv", index=False)

In [8]:
df

,COUNTRY,COUNTRY CODE,ISO CODES,POPULATION,AREA KM2,GDP $USD
0,Afghanistan,93,AF / AFG,"29,121,286","647,500",20.65 Billion
1,Albania,355,AL / ALB,"2,986,952","28,748",12.8 Billion
2,Algeria,213,DZ / DZA,"34,586,184","2,381,740",215.7 Billion
3,American Samoa,1-684,AS / ASM,"57,881",199,462.2 Million
4,Andorra,376,AD / AND,"84,000",468,4.8 Billion
...,...,...,...,...,...,...
235,Wallis and Futuna,681,WF / WLF,"16,025",274,
236,Western Sahara,212,EH / ESH,"273,008","266,000",
237,Yemen,967,YE / YEM,"23,495,361","527,970",43.89 Billion
238,Zambia,260,ZM / ZMB,"13,460,305","752,614",22.24 Billion
239,Zimbabwe,263,ZW / ZWE,"11,651,858","390,580",10.48 Billion